package telas;
import Classes.Cliente;
import Classes.Sistema;
import Classes.Usuario;
import java.io.*;
import telas.TelaPrincipal;
import java.util.*;
import javax.swing.*;
/**
 *
 * @author eduar
 */
public class Cadastro extends javax.swing.JFrame {
    Sistema sistema = new Sistema();
    boolean mostra = false;
    public Cadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblUsuarioCadastro = new javax.swing.JLabel();
        lblSenhaCadastro = new javax.swing.JLabel();
        txtConfirmaCadastro = new javax.swing.JToggleButton();
        txtUsuarioCadastro = new javax.swing.JTextField();
        txtEmailCadastro = new javax.swing.JTextField();
        labelSenha = new javax.swing.JLabel();
        txtSenhaCadastro = new javax.swing.JPasswordField();
        lblEmailCadastro = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(720, 512));
        setSize(new java.awt.Dimension(720, 512));

        jPanel1.setBackground(new java.awt.Color(23, 23, 23));
        jPanel1.setPreferredSize(new java.awt.Dimension(720, 512));
        jPanel1.setLayout(null);

        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Logo MangaTeca Pequena.png"))); // NOI18N
        jPanel1.add(lblTitulo);
        lblTitulo.setBounds(130, 80, 454, 67);

        lblUsuarioCadastro.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblUsuarioCadastro.setForeground(new java.awt.Color(237, 237, 237));
        lblUsuarioCadastro.setText("Nome de Usuário");
        jPanel1.add(lblUsuarioCadastro);
        lblUsuarioCadastro.setBounds(130, 230, 200, 32);

        lblSenhaCadastro.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblSenhaCadastro.setForeground(new java.awt.Color(237, 237, 237));
        lblSenhaCadastro.setText("Senha");
        jPanel1.add(lblSenhaCadastro);
        lblSenhaCadastro.setBounds(130, 310, 96, 32);

        txtConfirmaCadastro.setBackground(new java.awt.Color(218, 0, 55));
        txtConfirmaCadastro.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtConfirmaCadastro.setForeground(new java.awt.Color(237, 237, 237));
        txtConfirmaCadastro.setText("Finalizar Cadastro");
        txtConfirmaCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConfirmaCadastroActionPerformed(evt);
            }
        });
        jPanel1.add(txtConfirmaCadastro);
        txtConfirmaCadastro.setBounds(250, 410, 240, 47);

        txtUsuarioCadastro.setBackground(new java.awt.Color(68, 68, 68));
        txtUsuarioCadastro.setForeground(new java.awt.Color(237, 237, 237));
        txtUsuarioCadastro.setToolTipText("");
        jPanel1.add(txtUsuarioCadastro);
        txtUsuarioCadastro.setBounds(130, 270, 454, 30);

        txtEmailCadastro.setBackground(new java.awt.Color(68, 68, 68));
        txtEmailCadastro.setForeground(new java.awt.Color(237, 237, 237));
        txtEmailCadastro.setToolTipText("");
        jPanel1.add(txtEmailCadastro);
        txtEmailCadastro.setBounds(130, 190, 454, 30);

        labelSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Olho aberto.png"))); // NOI18N
        labelSenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelSenhaMouseClicked(evt);
            }
        });
        jPanel1.add(labelSenha);
        labelSenha.setBounds(550, 350, 30, 40);

        txtSenhaCadastro.setBackground(new java.awt.Color(68, 68, 68));
        txtSenhaCadastro.setForeground(new java.awt.Color(237, 237, 237));
        txtSenhaCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaCadastroActionPerformed(evt);
            }
        });
        jPanel1.add(txtSenhaCadastro);
        txtSenhaCadastro.setBounds(130, 350, 454, 40);

        lblEmailCadastro.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblEmailCadastro.setForeground(new java.awt.Color(237, 237, 237));
        lblEmailCadastro.setText("E-mail");
        jPanel1.add(lblEmailCadastro);
        lblEmailCadastro.setBounds(130, 150, 96, 32);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Voltar");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(70, 40, 60, 20);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/return.png"))); // NOI18N
        jLabel8.setText("jLabel8");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(30, 40, 40, 29);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtConfirmaCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConfirmaCadastroActionPerformed
        String txtEmail = txtEmailCadastro.getText();
        String txtUser = txtUsuarioCadastro.getText();
        String txtSenha = txtSenhaCadastro.getText();
        if(txtEmail.equals("")||txtUser.equals("")||txtSenha.equals("")){
            JOptionPane.showMessageDialog(null, "Preencha todos os campos antes de continuar." ,"Erro ao cadastrar", JOptionPane.INFORMATION_MESSAGE);
        } else {
            Usuario.Cadastrar(txtUser, txtEmail, txtSenha);  
        }
    }//GEN-LAST:event_txtConfirmaCadastroActionPerformed

    private void txtSenhaCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaCadastroActionPerformed

    }//GEN-LAST:event_txtSenhaCadastroActionPerformed

    private void labelSenhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelSenhaMouseClicked
        if(mostra==false){
            labelSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Olho fechado.png")));
            txtSenhaCadastro.setEchoChar((char)0);
            mostra = true;
        }else{
            labelSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Olho aberto.png")));
            txtSenhaCadastro.setEchoChar('\u25cf');
            mostra = false;
        }
    }//GEN-LAST:event_labelSenhaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelSenha;
    private javax.swing.JLabel lblEmailCadastro;
    private javax.swing.JLabel lblSenhaCadastro;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUsuarioCadastro;
    private javax.swing.JToggleButton txtConfirmaCadastro;
    private javax.swing.JTextField txtEmailCadastro;
    private javax.swing.JPasswordField txtSenhaCadastro;
    private javax.swing.JTextField txtUsuarioCadastro;
    // End of variables declaration//GEN-END:variables
}
