/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import Classes.Acao;
import Classes.Avaliacao;
import Classes.Comedia;
import Classes.Manga;
import Classes.Romance;
import Classes.Sistema;
import java.awt.Cursor;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author eduar
 */
public class ConfigAdm extends javax.swing.JFrame {

    String modo = "adicionar";
    DefaultTableModel model = new DefaultTableModel();
    public ConfigAdm() {
        initComponents();
        btnRemover.setEnabled(false);
        btnEditar.setEnabled(false);
        ArrayList<Manga> listaMangas = Sistema.ListarMangas();
        model.addColumn("ID");
        model.addColumn("Título");
        model.addColumn("Autor");
        model.addColumn("Gênero");
        model.addColumn("Preço");
        model.addColumn("Estoque");
        for (Manga manga : listaMangas) {
            model.addRow(new Object[]{
                manga.getId(),
                manga.getTitulo(),
                manga.getAutor(),
                manga.getGenero().getTipo(),
                manga.getPreco(),
                manga.getEstoque()
            });
        }
        tableMangas.setModel(model);
        if (tableMangas.getColumnModel().getColumnCount() > 0) {
            tableMangas.getColumnModel().getColumn(0).setMinWidth(40);
            tableMangas.getColumnModel().getColumn(0).setPreferredWidth(40);
            tableMangas.getColumnModel().getColumn(0).setMaxWidth(40);
            tableMangas.getColumnModel().getColumn(2).setMinWidth(120);
            tableMangas.getColumnModel().getColumn(2).setPreferredWidth(120);
            tableMangas.getColumnModel().getColumn(2).setMaxWidth(120);
            tableMangas.getColumnModel().getColumn(3).setMaxWidth(70);
            tableMangas.getColumnModel().getColumn(3).setPreferredWidth(70);
            tableMangas.getColumnModel().getColumn(3).setMinWidth(70);
            tableMangas.getColumnModel().getColumn(3).setMaxWidth(60);
            tableMangas.getColumnModel().getColumn(4).setMinWidth(65);
            tableMangas.getColumnModel().getColumn(4).setPreferredWidth(65);
            tableMangas.getColumnModel().getColumn(4).setMaxWidth(65);
            tableMangas.getColumnModel().getColumn(5).setMinWidth(70);
            tableMangas.getColumnModel().getColumn(5).setPreferredWidth(70);
            tableMangas.getColumnModel().getColumn(5).setMaxWidth(70);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSinopse = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnRemover = new javax.swing.JToggleButton();
        btnAdicionar = new javax.swing.JToggleButton();
        btnEditar = new javax.swing.JToggleButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableMangas = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        txtEstoque = new javax.swing.JTextField();
        comboGenero = new javax.swing.JComboBox<>();
        txtLinkImagem = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        lblModo = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txtAutor = new javax.swing.JTextField();
        txtPreco = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(820, 612));

        jPanel1.setBackground(new java.awt.Color(23, 23, 23));
        jPanel1.setMinimumSize(new java.awt.Dimension(820, 612));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(68, 68, 68));
        jPanel2.setMinimumSize(new java.awt.Dimension(211, 313));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(237, 237, 237));
        jLabel6.setText("Administrador");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/admin.png"))); // NOI18N

        jPanel4.setBackground(new java.awt.Color(60, 60, 60));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel4MouseEntered(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(219, 1, 55));
        jLabel8.setText("Log out");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel8)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel8)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(237, 237, 237));
        jLabel1.setText("Nome de Usuário:");

        jButton1.setText("Gerar Relatório de Vendas");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 290, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(301, 301, 301)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(402, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 252, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(146, 146, 146)
                    .addComponent(jLabel1)
                    .addContainerGap(147, Short.MAX_VALUE)))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 820, 60);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(237, 237, 237));
        jLabel2.setText("Sinopse");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(460, 100, 50, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(237, 237, 237));
        jLabel5.setText("Administrar Mangás");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(260, 60, 250, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(237, 237, 237));
        jLabel3.setText("Título");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 100, 40, 20);

        txtTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTituloActionPerformed(evt);
            }
        });
        txtTitulo.addKeyListener(new KeyAdapter() {
            private final String whitelist = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-._+,*= ";
            @Override
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if (whitelist.indexOf(c) < 0) {
                    e.consume(); // Ignora o caractere se não estiver na lista permitida
                }
            }
        });
        jPanel1.add(txtTitulo);
        txtTitulo.setBounds(10, 120, 430, 22);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(237, 237, 237));
        jLabel7.setText("Id");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(390, 150, 20, 20);

        txtSinopse.setColumns(1);
        txtSinopse.setLineWrap(true);
        txtSinopse.setRows(5);
        txtSinopse.setText("Chiyo Mihama é uma criança prodígio que pulou várias séries para terminar o ensino médio. No primeiro dia, ela descobre que sua turma está cheia de indivíduos excêntricos. À medida que as colegas se tornam boas amigas ao longo do tempo, elas vivenciam a vida cotidiana juntos – coisas como escola, estudo, viagens de verão e envolvimento em todos os tipos de travessuras!\n\n");
        jScrollPane1.setViewportView(txtSinopse);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(460, 120, 350, 130);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(237, 237, 237));
        jLabel9.setText("Autor");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(10, 150, 50, 20);

        txtId.setEditable(false);
        txtId.setEnabled(false);
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        jPanel1.add(txtId);
        txtId.setBounds(390, 170, 40, 22);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(237, 237, 237));
        jLabel10.setText("Preço");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(10, 200, 50, 20);

        btnRemover.setBackground(new java.awt.Color(218, 0, 55));
        btnRemover.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnRemover.setForeground(new java.awt.Color(237, 237, 237));
        btnRemover.setText("Remover");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });
        jPanel1.add(btnRemover);
        btnRemover.setBounds(520, 270, 170, 40);

        btnAdicionar.setBackground(new java.awt.Color(218, 0, 55));
        btnAdicionar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnAdicionar.setForeground(new java.awt.Color(237, 237, 237));
        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdicionar);
        btnAdicionar.setBounds(80, 270, 170, 40);

        btnEditar.setBackground(new java.awt.Color(218, 0, 55));
        btnEditar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnEditar.setForeground(new java.awt.Color(237, 237, 237));
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditar);
        btnEditar.setBounds(290, 270, 170, 40);

        tableMangas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Título", "Autor", "Sinopse", "Preço", "Estoque"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableMangas);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(0, 330, 820, 280);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(237, 237, 237));
        jLabel11.setText("Link da Imagem");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(170, 200, 100, 20);

        txtEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstoqueActionPerformed(evt);
            }
        });
        txtEstoque.addKeyListener(new KeyAdapter() {
            private final String whitelist = "0123456789";
            @Override
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if (whitelist.indexOf(c) < 0) {
                    e.consume(); // Ignora o caractere se não estiver na lista permitida
                }
            }
        });
        jPanel1.add(txtEstoque);
        txtEstoque.setBounds(90, 220, 60, 22);

        comboGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Romance", "Ação", "Comédia" }));
        jPanel1.add(comboGenero);
        comboGenero.setBounds(280, 170, 90, 22);

        txtLinkImagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLinkImagemActionPerformed(evt);
            }
        });
        txtLinkImagem.addKeyListener(new KeyAdapter() {
            private final String whitelist = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-._+,*=";
            @Override
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if (whitelist.indexOf(c) < 0) {
                    e.consume(); // Ignora o caractere se não estiver na lista permitida
                }
            }
        });
        jPanel1.add(txtLinkImagem);
        txtLinkImagem.setBounds(170, 220, 260, 22);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(237, 237, 237));
        jLabel12.setText("Estoque");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(90, 200, 50, 20);

        lblModo.setForeground(new java.awt.Color(237, 237, 237));
        lblModo.setText("Modo Atual: Adicionar mangá");
        jPanel1.add(lblModo);
        lblModo.setBounds(560, 70, 170, 16);

        jButton2.setText("Mudar Modo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(580, 90, 110, 20);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(237, 237, 237));
        jLabel13.setText("Gênero");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(280, 150, 50, 20);

        txtAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAutorActionPerformed(evt);
            }
        });
        jPanel1.add(txtAutor);
        txtAutor.setBounds(10, 170, 260, 22);

        txtPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecoActionPerformed(evt);
            }
        });
        txtPreco.addKeyListener(new KeyAdapter() {
            private final String whitelist = "0123456789.";
            @Override
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if (whitelist.indexOf(c) < 0) {
                    e.consume(); // Ignora o caractere se não estiver na lista permitida
                }
            }
        });
        jPanel1.add(txtPreco);
        txtPreco.setBounds(10, 220, 60, 22);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseEntered
        jPanel4.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jPanel4MouseEntered

    private void txtTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTituloActionPerformed

    }//GEN-LAST:event_txtTituloActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed

    }//GEN-LAST:event_btnRemoverActionPerformed

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        String titulo = txtTitulo.getText();
        String autor = txtAutor.getText();
        var gen = (String) comboGenero.getSelectedItem();
        double preco = Double.parseDouble(txtPreco.getText());
        String linkImagem = txtLinkImagem.getText();
        int estoque = Integer.parseInt(txtEstoque.getText());
        String sinopse = txtSinopse.getText();
        ArrayList<Avaliacao> avaliacoes = new ArrayList<>();
        if (gen.equals("Ação")){
            Acao genero = new Acao("Acao");
            Manga manga = new Manga(1, titulo, sinopse, genero, autor, estoque, preco, avaliacoes, linkImagem);
            model.addRow(new Object[]{
                manga.getId(),
                manga.getTitulo(),
                manga.getAutor(),
                manga.getGenero().getTipo(),
                manga.getPreco(),
                manga.getEstoque()
            });
        } else if (gen.equals("Comédia")){
            Comedia genero = new Comedia("Comedia");
            Manga manga = new Manga(1, titulo, sinopse, genero, autor, estoque, preco, avaliacoes, linkImagem);
            model.addRow(new Object[]{
                manga.getId(),
                manga.getTitulo(),
                manga.getAutor(),
                manga.getGenero().getTipo(),
                manga.getPreco(),
                manga.getEstoque()
            });
        } else if (gen.equals("Romance")){
            Romance genero = new Romance("Romance");
            Manga manga = new Manga(1, titulo, sinopse, genero, autor, estoque, preco, avaliacoes, linkImagem);
            model.addRow(new Object[]{
                manga.getId(),
                manga.getTitulo(),
                manga.getAutor(),
                manga.getGenero().getTipo(),
                manga.getPreco(),
                manga.getEstoque()
            });
        }
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarActionPerformed

    private void txtEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstoqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstoqueActionPerformed

    private void txtLinkImagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLinkImagemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLinkImagemActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(modo.equals("adicionar")){
            modo = "editar";
            lblModo.setText("Modo Atual: Editar mangá");
            btnEditar.setEnabled(true);
            btnAdicionar.setEnabled(false);
        } else if (modo.equals("editar")){
            modo = "remover";
            lblModo.setText("Modo Atual: Remover mangá");
            btnEditar.setEnabled(false);
            btnRemover.setEnabled(true);
        } else if (modo.equals("remover")){
            modo = "adicionar";
            lblModo.setText("Modo Atual: Adicionar mangá");
            btnAdicionar.setEnabled(true);
            btnRemover.setEnabled(false);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAutorActionPerformed

    private void txtPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfigAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfigAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfigAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfigAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfigAdm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnAdicionar;
    private javax.swing.JToggleButton btnEditar;
    private javax.swing.JToggleButton btnRemover;
    private javax.swing.JComboBox<String> comboGenero;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblModo;
    private javax.swing.JTable tableMangas;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtEstoque;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtLinkImagem;
    private javax.swing.JFormattedTextField txtPreco;
    private javax.swing.JTextArea txtSinopse;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
